
#ifndef KRITAQMICINTERFACE_EXPORT_H
#define KRITAQMICINTERFACE_EXPORT_H

#ifdef KRITAQMICINTERFACE_STATIC_DEFINE
#  define KRITAQMICINTERFACE_EXPORT
#  define KRITAQMICINTERFACE_NO_EXPORT
#else
#  ifndef KRITAQMICINTERFACE_EXPORT
#    ifdef kritaqmicinterface_EXPORTS
        /* We are building this library */
#      define KRITAQMICINTERFACE_EXPORT __attribute__((visibility("default")))
#    else
        /* We are using this library */
#      define KRITAQMICINTERFACE_EXPORT __attribute__((visibility("default")))
#    endif
#  endif

#  ifndef KRITAQMICINTERFACE_NO_EXPORT
#    define KRITAQMICINTERFACE_NO_EXPORT __attribute__((visibility("hidden")))
#  endif
#endif

#ifndef KRITAQMICINTERFACE_DEPRECATED
#  define KRITAQMICINTERFACE_DEPRECATED __attribute__ ((__deprecated__))
#endif

#ifndef KRITAQMICINTERFACE_DEPRECATED_EXPORT
#  define KRITAQMICINTERFACE_DEPRECATED_EXPORT KRITAQMICINTERFACE_EXPORT KRITAQMICINTERFACE_DEPRECATED
#endif

#ifndef KRITAQMICINTERFACE_DEPRECATED_NO_EXPORT
#  define KRITAQMICINTERFACE_DEPRECATED_NO_EXPORT KRITAQMICINTERFACE_NO_EXPORT KRITAQMICINTERFACE_DEPRECATED
#endif

/* NOLINTNEXTLINE(readability-avoid-unconditional-preprocessor-if) */
#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef KRITAQMICINTERFACE_NO_DEPRECATED
#    define KRITAQMICINTERFACE_NO_DEPRECATED
#  endif
#endif

#endif /* KRITAQMICINTERFACE_EXPORT_H */
