// SPDX-FileCopyrightText: 2026 Feather-Krita App Contributors
// SPDX-License-Identifier: GPL-2.0-or-later
//
// krita_bindings.dart — Dart FFI bindings to Krita C++ brush engine
//
// Bridges Flutter/Dart to the native `krita_bridge` shared library which
// calls Krita's public brush API (KisBrush, KisPaintOp, etc.).
//
// The high-level [KritaBrushEngine] wraps the raw FFI calls into a clean
// Dart-friendly API used by the engine layer.

import 'dart:ffi';
import 'dart:io';
import 'dart:typed_data';

import 'package:ffi/ffi.dart';

// ---------------------------------------------------------------------------
// Native struct mirrors — these layouts MUST match `krita_bridge.h`.
// ---------------------------------------------------------------------------

/// Mirrors `BrushInput` in `krita_bridge.h`.
///
/// Describes the state of the stylus / pointer at one instant in time. The
/// layout is identical to the C struct: 6 doubles + 2 floats + 2 int32
/// (flags + explicit padding), total 64 bytes.
final class BrushInputNative extends Struct {
  /// X position in device-independent pixels relative to the dab origin.
  @Double()
  external double x;

  /// Y position in device-independent pixels relative to the dab origin.
  @Double()
  external double y;

  /// Normalized pressure in range [0, 1] (1.0 == max pressure).
  @Double()
  external double pressure;

  /// X tilt in degrees, range [-90, 90].
  @Double()
  external double tiltX;

  /// Y tilt in degrees, range [-90, 90].
  @Double()
  external double tiltY;

  /// Time in seconds since stroke start.
  @Double()
  external double time;

  /// Velocity along X axis (px/s).
  @Float()
  external double velocityX;

  /// Velocity along Y axis (px/s).
  @Float()
  external double velocityY;

  /// Bitfield of button/modifier flags (see [BrushInputFlags]).
  @Int32()
  external int flags;

  @Int32()
  // ignore: unused_field
  external int _padding;
}

/// Mirrors `BrushDab` in `krita_bridge.h`.
///
/// Represents a single stamp (dab) generated by Krita's brush engine. The
/// pixel buffer is allocated on the native side and owned by the bridge —
/// Dart must copy it out via [KritaBrushEngine._readDab] and then release
/// the buffer with `krita_brush_release_dab`.
final class BrushDabNative extends Struct {
  /// Width of the dab image in pixels.
  @Int32()
  external int width;

  /// Height of the dab image in pixels.
  @Int32()
  external int height;

  /// Number of bytes per pixel row (== width * 4 for RGBA8).
  @Int32()
  external int stride;

  /// Reserved for alignment / future use.
  @Int32()
  external int reserved;

  /// Pointer to width*height*4 bytes of RGBA8 pixel data (premultiplied).
  external Pointer<Uint8> pixels;
}

// ---------------------------------------------------------------------------
// High-level Dart value types.
// ---------------------------------------------------------------------------

/// Bit flags packed inside [BrushInputNative.flags].
class BrushInputFlags {
  const BrushInputFlags._(this.value);
  final int value;

  static const int kNone = 0;
  static const int kEraser = 1 << 0;
  static const int kSmudge = 1 << 1;
  static const int kMirrorX = 1 << 2;
  static const int kMirrorY = 1 << 3;
  static const int kInverted = 1 << 4;

  factory BrushInputFlags({
    bool eraser = false,
    bool smudge = false,
    bool mirrorX = false,
    bool mirrorY = false,
    bool inverted = false,
  }) {
    int v = kNone;
    if (eraser) v |= kEraser;
    if (smudge) v |= kSmudge;
    if (mirrorX) v |= kMirrorX;
    if (mirrorY) v |= kMirrorY;
    if (inverted) v |= kInverted;
    return BrushInputFlags._(v);
  }

  bool get eraser => (value & kEraser) != 0;
  bool get smudge => (value & kSmudge) != 0;
  bool get mirrorX => (value & kMirrorX) != 0;
  bool get mirrorY => (value & kMirrorY) != 0;
  bool get inverted => (value & kInverted) != 0;
}

/// Immutable Dart-side description of a brush input sample.
class BrushInput {
  final double x;
  final double y;
  final double pressure;
  final double tiltX;
  final double tiltY;
  final double time;
  final double velocityX;
  final double velocityY;
  final BrushInputFlags flags;

  const BrushInput({
    required this.x,
    required this.y,
    this.pressure = 0.5,
    this.tiltX = 0.0,
    this.tiltY = 0.0,
    this.time = 0.0,
    this.velocityX = 0.0,
    this.velocityY = 0.0,
    this.flags = const BrushInputFlags._(BrushInputFlags.kNone),
  });

  BrushInput copyWith({
    double? x,
    double? y,
    double? pressure,
    double? tiltX,
    double? tiltY,
    double? time,
    double? velocityX,
    double? velocityY,
    BrushInputFlags? flags,
  }) =>
      BrushInput(
        x: x ?? this.x,
        y: y ?? this.y,
        pressure: pressure ?? this.pressure,
        tiltX: tiltX ?? this.tiltX,
        tiltY: tiltY ?? this.tiltY,
        time: time ?? this.time,
        velocityX: velocityX ?? this.velocityX,
        velocityY: velocityY ?? this.velocityY,
        flags: flags ?? this.flags,
      );

  void _writeTo(BrushInputNative native) {
    native.x = x;
    native.y = y;
    native.pressure = pressure.clamp(0.0, 1.0);
    native.tiltX = tiltX;
    native.tiltY = tiltY;
    native.time = time;
    native.velocityX = velocityX;
    native.velocityY = velocityY;
    native.flags = flags.value;
    native._padding = 0;
  }
}

/// Immutable Dart-side description of a generated dab.
class BrushDab {
  final int width;
  final int height;
  final int stride;
  final Uint8List pixels; // RGBA8, length == height * stride

  const BrushDab({
    required this.width,
    required this.height,
    required this.stride,
    required this.pixels,
  });

  bool get isEmpty => width == 0 || height == 0 || pixels.isEmpty;
}

/// RGBA color value packed as 0xAARRGGBB.
class BrushColor {
  final int a;
  final int r;
  final int g;
  final int b;

  const BrushColor(this.r, this.g, this.b, [this.a = 255]);

  int get packed => (a << 24) | (r << 16) | (g << 8) | b;

  static BrushColor fromPacked(int packed) => BrushColor(
        (packed >> 16) & 0xff,
        (packed >> 8) & 0xff,
        packed & 0xff,
        (packed >> 24) & 0xff,
      );
}

// ---------------------------------------------------------------------------
// Raw FFI signatures.
// ---------------------------------------------------------------------------

typedef _KritaBrushInitNative = Pointer<Void> Function();
typedef _KritaBrushInitDart = Pointer<Void> Function();

typedef _KritaBrushDestroyNative = Void Function(Pointer<Void> handle);
typedef _KritaBrushDestroyDart = void Function(Pointer<Void> handle);

typedef _KritaBrushLoadPresetNative = Int32 Function(
    Pointer<Void> handle, Pointer<Utf8> path);
typedef _KritaBrushLoadPresetDart = int Function(
    Pointer<Void> handle, Pointer<Utf8> path);

typedef _KritaBrushSetSizeNative = Void Function(
    Pointer<Void> handle, Double size);
typedef _KritaBrushSetSizeDart = void Function(
    Pointer<Void> handle, double size);

typedef _KritaBrushSetColorNative = Void Function(
    Pointer<Void> handle, Uint32 argb);
typedef _KritaBrushSetColorDart = void Function(
    Pointer<Void> handle, int argb);

typedef _KritaBrushSetOpacityNative = Void Function(
    Pointer<Void> handle, Double opacity);
typedef _KritaBrushSetOpacityDart = void Function(
    Pointer<Void> handle, double opacity);

typedef _KritaBrushSetSpacingNative = Void Function(
    Pointer<Void> handle, Double spacing);
typedef _KritaBrushSetSpacingDart = void Function(
    Pointer<Void> handle, double spacing);

typedef _KritaBrushSetSmudgeNative = Void Function(
    Pointer<Void> handle, Double smudge);
typedef _KritaBrushSetSmudgeDart = void Function(
    Pointer<Void> handle, double smudge);

typedef _KritaBrushSetFlowNative = Void Function(
    Pointer<Void> handle, Double flow);
typedef _KritaBrushSetFlowDart = void Function(
    Pointer<Void> handle, double flow);

typedef _KritaBrushSetHardnessNative = Void Function(
    Pointer<Void> handle, Double hardness);
typedef _KritaBrushSetHardnessDart = void Function(
    Pointer<Void> handle, double hardness);

typedef _KritaBrushGenerateDabNative = Bool Function(Pointer<Void> handle,
    Pointer<BrushInputNative> input, Pointer<BrushDabNative> outDab);
typedef _KritaBrushGenerateDabDart = bool Function(Pointer<Void> handle,
    Pointer<BrushInputNative> input, Pointer<BrushDabNative> outDab);

typedef _KritaBrushReleaseDabNative = Void Function(
    Pointer<Void> handle, Pointer<BrushDabNative> dab);
typedef _KritaBrushReleaseDabDart = void Function(
    Pointer<Void> handle, Pointer<BrushDabNative> dab);

typedef _KritaBrushCleanupNative = Void Function(Pointer<Void> handle);
typedef _KritaBrushCleanupDart = void Function(Pointer<Void> handle);

typedef _KritaBrushLastErrorNative = Pointer<Utf8> Function(Pointer<Void> handle);
typedef _KritaBrushLastErrorDart = Pointer<Utf8> Function(Pointer<Void> handle);

typedef _KritaBrushGetSizeNative = Double Function(Pointer<Void> handle);
typedef _KritaBrushGetSizeDart = double Function(Pointer<Void> handle);

typedef _KritaBrushGetOpacityNative = Double Function(Pointer<Void> handle);
typedef _KritaBrushGetOpacityDart = double Function(Pointer<Void> handle);

typedef _KritaBrushGetSpacingNative = Double Function(Pointer<Void> handle);
typedef _KritaBrushGetSpacingDart = double Function(Pointer<Void> handle);

typedef _KritaBrushGetHardnessNative = Double Function(Pointer<Void> handle);
typedef _KritaBrushGetHardnessDart = double Function(Pointer<Void> handle);

typedef _KritaBrushGetFlowNative = Double Function(Pointer<Void> handle);
typedef _KritaBrushGetFlowDart = double Function(Pointer<Void> handle);

typedef _KritaBrushGetEraserNative = Bool Function(Pointer<Void> handle);
typedef _KritaBrushGetEraserDart = bool Function(Pointer<Void> handle);

typedef _KritaBrushGetPresetNameNative = Pointer<Utf8> Function(
    Pointer<Void> handle);
typedef _KritaBrushGetPresetNameDart = Pointer<Utf8> Function(
    Pointer<Void> handle);

// ---------------------------------------------------------------------------
// Dynamic library loader.
// ---------------------------------------------------------------------------

/// Loads the `krita_bridge` native library for the current platform.
///
/// On Android the library is bundled inside the APK and Android loads it
/// automatically. On desktop platforms we resolve a system path.
DynamicLibrary _loadKritaBridge() {
  if (Platform.isAndroid || Platform.isIOS) {
    return DynamicLibrary.open('libkrita_bridge.so');
  }
  if (Platform.isWindows) {
    // Try a few candidate locations next to the executable.
    final candidates = <String>[
      'krita_bridge.dll',
      'lib\\krita_bridge.dll',
      '.\\krita_bridge.dll',
    ];
    for (final c in candidates) {
      try {
        return DynamicLibrary.open(c);
      } on ArgumentError {
        // continue
      }
    }
    throw StateError('krita_bridge.dll not found in search path');
  }
  if (Platform.isLinux) {
    // Try several candidate locations: alongside the executable, in the
    // bundle's lib folder, in a dev path, and finally the bare name (which
    // relies on LD_LIBRARY_PATH).
    final candidates = <String>[
      'lib/libkrita_bridge.so',
      'libkrita_bridge.so',
      './libkrita_bridge.so',
      'assets/native/linux/libkrita_bridge.so',
      'assets/native/libkrita_bridge.so',
      '../assets/native/linux/libkrita_bridge.so',
    ];
    for (final c in candidates) {
      try {
        return DynamicLibrary.open(c);
      } on ArgumentError {
        // continue
      } on OSError {
        // continue
      }
    }
    throw StateError('libkrita_bridge.so not found. Set LD_LIBRARY_PATH or '
        'place the .so next to the executable.');
  }
  if (Platform.isMacOS) {
    return DynamicLibrary.open('libkrita_bridge.dylib');
  }
  throw UnsupportedError('Krita bridge not supported on this platform');
}

// ---------------------------------------------------------------------------
// High-level wrapper.
// ---------------------------------------------------------------------------

/// High-level Dart wrapper around the Krita C++ brush engine.
///
/// Owns a native brush handle and exposes a small set of methods used by the
/// Feather-Krita engine layer. The class is not re-entrant — callers must
/// ensure that brush operations are serialized.
///
/// Typical usage:
/// ```dart
/// final engine = KritaBrushEngine();
/// await engine.loadPreset('/path/to/brush.kpp');
/// engine.size = 32;
/// engine.color = const BrushColor(0, 0, 0);
/// final dab = engine.generateDab(BrushInput(x: 10, y: 20, pressure: 0.8));
/// engine.dispose();
/// ```
class KritaBrushEngine {
  KritaBrushEngine._(this._lib, this._handle);

  static DynamicLibrary? _cachedLib;

  /// Constructs a new engine instance, loading the native library and
  /// allocating a fresh brush handle.
  factory KritaBrushEngine() {
    final lib = _cachedLib ??= _loadKritaBridge();
    final init = lib.lookupFunction<_KritaBrushInitNative, _KritaBrushInitDart>(
        'krita_brush_init');
    final handle = init();
    if (handle == nullptr) {
      throw StateError('krita_brush_init returned a null handle');
    }
    return KritaBrushEngine._(lib, handle);
  }

  final DynamicLibrary _lib;
  final Pointer<Void> _handle;
  bool _disposed = false;

  // Cached lookups (lazy — they only resolve on first use).
  late final _KritaBrushDestroyDart _destroy =
      _lib.lookupFunction<_KritaBrushDestroyNative, _KritaBrushDestroyDart>(
          'krita_brush_destroy');
  late final _KritaBrushLoadPresetDart _loadPreset = _lib
      .lookupFunction<_KritaBrushLoadPresetNative, _KritaBrushLoadPresetDart>(
          'krita_brush_load_preset');
  late final _KritaBrushSetSizeDart _setSize = _lib
      .lookupFunction<_KritaBrushSetSizeNative, _KritaBrushSetSizeDart>(
          'krita_brush_set_size');
  late final _KritaBrushSetColorDart _setColor = _lib
      .lookupFunction<_KritaBrushSetColorNative, _KritaBrushSetColorDart>(
          'krita_brush_set_color');
  late final _KritaBrushSetOpacityDart _setOpacity = _lib
      .lookupFunction<_KritaBrushSetOpacityNative, _KritaBrushSetOpacityDart>(
          'krita_brush_set_opacity');
  late final _KritaBrushSetSpacingDart _setSpacing = _lib
      .lookupFunction<_KritaBrushSetSpacingNative, _KritaBrushSetSpacingDart>(
          'krita_brush_set_spacing');
  late final _KritaBrushSetSmudgeDart _setSmudge = _lib
      .lookupFunction<_KritaBrushSetSmudgeNative, _KritaBrushSetSmudgeDart>(
          'krita_brush_set_smudge');
  late final _KritaBrushSetFlowDart _setFlow = _lib
      .lookupFunction<_KritaBrushSetFlowNative, _KritaBrushSetFlowDart>(
          'krita_brush_set_flow');
  late final _KritaBrushSetHardnessDart _setHardness = _lib
      .lookupFunction<_KritaBrushSetHardnessNative, _KritaBrushSetHardnessDart>(
          'krita_brush_set_hardness');
  late final _KritaBrushGenerateDabDart _generateDab = _lib.lookupFunction<
      _KritaBrushGenerateDabNative,
      _KritaBrushGenerateDabDart>('krita_brush_generate_dab');
  late final _KritaBrushReleaseDabDart _releaseDab = _lib
      .lookupFunction<_KritaBrushReleaseDabNative, _KritaBrushReleaseDabDart>(
          'krita_brush_release_dab');
  late final _KritaBrushCleanupDart _cleanup = _lib
      .lookupFunction<_KritaBrushCleanupNative, _KritaBrushCleanupDart>(
          'krita_brush_cleanup');
  late final _KritaBrushLastErrorDart _lastError = _lib
      .lookupFunction<_KritaBrushLastErrorNative, _KritaBrushLastErrorDart>(
          'krita_brush_last_error');

  /// Loads a Krita brush preset (.kpp) from the filesystem.
  ///
  /// Returns `true` on success. On failure [lastError] will contain a
  /// description. After a successful load, read [currentSize],
  /// [currentOpacity] and [currentSpacing] to reflect the preset's values
  /// in the app UI.
  bool loadPreset(String path) {
    _checkAlive();
    final pathPtr = path.toNativeUtf8();
    try {
      final r = _loadPreset(_handle, pathPtr);
      return r == 0;
    } finally {
      calloc.free(pathPtr);
    }
  }

  // ----- Parameter getters (reflect loaded presets into the UI) ----------

  late final _KritaBrushGetSizeDart _getSize =
      _lib.lookupFunction<_KritaBrushGetSizeNative, _KritaBrushGetSizeDart>(
          'krita_brush_get_size');
  late final _KritaBrushGetOpacityDart _getOpacity =
      _lib.lookupFunction<_KritaBrushGetOpacityNative, _KritaBrushGetOpacityDart>(
          'krita_brush_get_opacity');
  late final _KritaBrushGetSpacingDart _getSpacing =
      _lib.lookupFunction<_KritaBrushGetSpacingNative, _KritaBrushGetSpacingDart>(
          'krita_brush_get_spacing');
  late final _KritaBrushGetHardnessDart _getHardness =
      _lib.lookupFunction<_KritaBrushGetHardnessNative, _KritaBrushGetHardnessDart>(
          'krita_brush_get_hardness');
  late final _KritaBrushGetFlowDart _getFlow =
      _lib.lookupFunction<_KritaBrushGetFlowNative, _KritaBrushGetFlowDart>(
          'krita_brush_get_flow');
  late final _KritaBrushGetEraserDart _getEraser =
      _lib.lookupFunction<_KritaBrushGetEraserNative, _KritaBrushGetEraserDart>(
          'krita_brush_get_eraser');
  late final _KritaBrushGetPresetNameDart _getPresetName =
      _lib.lookupFunction<_KritaBrushGetPresetNameNative, _KritaBrushGetPresetNameDart>(
          'krita_brush_get_preset_name');

  /// The brush diameter currently set on the native engine.
  double get currentSize {
    _checkAlive();
    return _getSize(_handle);
  }

  /// The flow / opacity currently set on the native engine.
  double get currentOpacity {
    _checkAlive();
    return _getOpacity(_handle);
  }

  /// The dab spacing currently set on the native engine.
  double get currentSpacing {
    _checkAlive();
    return _getSpacing(_handle);
  }

  /// The hardness currently set on the native engine.
  double get currentHardness {
    _checkAlive();
    return _getHardness(_handle);
  }

  /// The flow (per-dab application rate) currently set on the native
  /// engine, in [0, 1] (default 1.0). Reflects either a [flow] setter
  /// call or a preset's FlowValue sensor base. Flow < 1 scales each
  /// dab's alpha so paint builds up gradually over multiple stamps.
  double get currentFlow {
    _checkAlive();
    return _getFlow(_handle);
  }

  /// Whether the loaded preset is an eraser preset (settings-level
  /// Krita/erase, EraserMode or CompositeOp=erase). Stroke compositing
  /// should switch to destination-out while this is true.
  bool get isEraserPreset {
    _checkAlive();
    return _getEraser(_handle);
  }

  /// The name of the last successfully loaded preset, or '' if none.
  String get currentPresetName {
    _checkAlive();
    final ptr = _getPresetName(_handle);
    if (ptr == nullptr) return '';
    return ptr.toDartString();
  }

  /// Sets the brush diameter in pixels.
  set size(double pixels) {
    _checkAlive();
    _setSize(_handle, pixels);
  }

  /// Sets the brush color.
  set color(BrushColor c) {
    _checkAlive();
    _setColor(_handle, c.packed);
  }

  /// Sets the brush flow / opacity in range [0, 1].
  set opacity(double value) {
    _checkAlive();
    _setOpacity(_handle, value.clamp(0.0, 1.0));
  }

  /// Sets the dab spacing (fraction of brush diameter) in range [0, 5].
  set spacing(double value) {
    _checkAlive();
    _setSpacing(_handle, value.clamp(0.0, 5.0));
  }

  /// Sets the smudge ratio in range [0, 1] (0 == no smudge, 1 == pure smudge).
  set smudge(double value) {
    _checkAlive();
    _setSmudge(_handle, value.clamp(0.0, 1.0));
  }

  /// Sets the brush flow (per-dab application rate) in range [0, 1].
  /// Flow < 1 scales each dab's alpha so paint builds up gradually over
  /// multiple stamps. Distinct from [opacity] (the master multiplier
  /// applied by the host compositor).
  set flow(double value) {
    _checkAlive();
    _setFlow(_handle, value.clamp(0.0, 1.0));
  }

  /// Sets the brush hardness in range [0, 1] (0 = fully soft gaussian
  /// falloff, 1 = hard-edged disk). On the real engine this rebuilds
  /// the mask generator's fade.
  set hardness(double value) {
    _checkAlive();
    _setHardness(_handle, value.clamp(0.0, 1.0));
  }

  /// Generates a single dab image for the given input.
  ///
  /// The returned [BrushDab] owns a copy of the pixel data, so callers may
  /// hold onto it indefinitely. Returns an empty dab if the engine rejects
  /// the input (e.g. zero pressure and skip-on-zero enabled).
  BrushDab generateDab(BrushInput input) {
    _checkAlive();
    final inputPtr = calloc<BrushInputNative>();
    final dabPtr = calloc<BrushDabNative>();
    try {
      input._writeTo(inputPtr.ref);
      dabPtr.ref.width = 0;
      dabPtr.ref.height = 0;
      dabPtr.ref.stride = 0;
      dabPtr.ref.reserved = 0;
      dabPtr.ref.pixels = nullptr;

      final ok = _generateDab(_handle, inputPtr, dabPtr);
      if (!ok) {
        return BrushDab(width: 0, height: 0, stride: 0, pixels: Uint8List(0));
      }
      final w = dabPtr.ref.width;
      final h = dabPtr.ref.height;
      final stride = dabPtr.ref.stride == 0 ? w * 4 : dabPtr.ref.stride;
      final pixelsPtr = dabPtr.ref.pixels;
      if (w <= 0 || h <= 0 || pixelsPtr == nullptr) {
        return BrushDab(width: 0, height: 0, stride: 0, pixels: Uint8List(0));
      }
      final byteCount = stride * h;
      // Copy the native pixel buffer into a Dart-owned Uint8List so the
      // data remains valid after we release the native dab.
      final pixels = Uint8List.fromList(pixelsPtr.asTypedList(byteCount));

      // Release the native buffer now that we have our own copy.
      _releaseDab(_handle, dabPtr);
      dabPtr.ref.pixels = nullptr;

      return BrushDab(width: w, height: h, stride: stride, pixels: pixels);
    } finally {
      calloc.free(inputPtr);
      // If generate_dab failed the pointer may still be null but freeing it
      // is safe.
      if (dabPtr.ref.pixels != nullptr) {
        _releaseDab(_handle, dabPtr);
      }
      calloc.free(dabPtr);
    }
  }

  /// Resets the internal stroke state (called between strokes).
  void cleanup() {
    _checkAlive();
    _cleanup(_handle);
  }

  /// Returns the most recent error message produced by the engine, or an
  /// empty string if there is none.
  String lastError() {
    _checkAlive();
    final ptr = _lastError(_handle);
    if (ptr == nullptr) return '';
    final msg = ptr.toDartString();
    return msg;
  }

  /// Releases the native brush handle. After this the instance is unusable.
  void dispose() {
    if (_disposed) return;
    _disposed = true;
    _cleanup(_handle);
    _destroy(_handle);
  }

  void _checkAlive() {
    if (_disposed) {
      throw StateError('KritaBrushEngine has been disposed');
    }
  }
}
